ProyectoB/Models/oportunidades.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class oportunidades
    {

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public oportunidades()
        {
            this.actividad = new HashSet<actividad>();
            this.fecha_creacion = System.DateTime.Now;
            this.fecha_vencimiento = System.DateTime.Now;
        }

        public int id { get; set; }

        [Display(Name = "ID Contacto Empresa")]
        [Required(ErrorMessage = "Seleccione Empresa")]
        [Range(1, int.MaxValue, ErrorMessage = "Seleccione Contacto")]
        public int id_contacto_empresa { get; set; }
        [Display(Name = "ID Usuario")]
        [Required(ErrorMessage = "Seleccione Usuario")]
        public int id_contacto_asignado { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "Fecha de creación")]
        [Required(ErrorMessage = "Debe seleccionar Fecha de Creación")]
        public System.DateTime fecha_creacion { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "Fecha de vencimiento")]
        [Required(ErrorMessage = "Debe seleccionar Fecha de Vencimiento")]
        public System.DateTime fecha_vencimiento { get; set; }

        [Display(Name = "Cupos")]
        [Range(0, 100, ErrorMessage = "Los cupos deben estar entre 0 y 100")]
        [DataType(DataType.Text)]
        public int cupos { get; set; }


        [Display(Name = "Tema")]
        [Required(ErrorMessage = "Debe seleccionar Tema")]
        public string tema { get; set; }
        [Display(Name = "Estado")]
        public string estado { get; set; }
        public bool isSelected { get; set; }

        public List<SelectListItem> Temas = new List<SelectListItem>()
        {       new SelectListItem() {Text="Cupo", Value="cupo"},
                new SelectListItem() { Text="Financiamiento", Value="financiamiento"},
                new SelectListItem() { Text="Otro", Value="otro"}
        };

        public List<SelectListItem> Estados = new List<SelectListItem>()
        {
                new SelectListItem() {Text="Lograda", Value="lograda"},
                new SelectListItem() { Text="Activa", Value="activa"},
                new SelectListItem() { Text="Perdida", Value="perdida"}
        };

        public List<usuario> usuarioList;
        public List<contacto_empresa> contacto_empresaList;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<actividad> actividad { get; set; }
        public virtual contacto_empresa contacto_empresa { get; set; }
        public virtual usuario usuario { get; set; }

        public List<SelectListItem> usuarioListI { get; internal set; }
        public List<SelectListItem> contacto_empresaListI { get; internal set; }
        public List<empresa> EmpresaModel { get; set; }



    }
}

ProyectoB/Controllers/ActividadesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.Entity;
using PagedList;
using WebApplication9.Models;
using System.Net;

namespace WebApplication9.Controllers
{
    public class ActividadesController : Controller
    {
        string creada = System.Web.HttpContext.Current.Session["Name"].ToString();

        // GET: Actividades
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Index_Actividades(int? page,string search, int? nn, string sortBy)
        {
            List<actividad> listaActividad = new List<actividad>();
            using (proyectob_dbEntities dbModel = new proyectob_dbEntities())
            {
                ViewBag.NumeroR = new List<SelectListItem>()

                  {
                    new SelectListItem() {Text="10", Value="10"},
                    new SelectListItem() {Text="20", Value="20"},
                    new SelectListItem() {Text="40", Value="40"},
                    new SelectListItem() {Text="60", Value="60"},
                    new SelectListItem() {Text="100", Value="100"},
                    new SelectListItem() {Text="200", Value="200"},
                    new SelectListItem() {Text="500", Value="500"},
                    new SelectListItem() {Text="1000", Value="1000"},
                    new SelectListItem() {Text="2000", Value="2000"},
                    new SelectListItem() {Text="5000", Value="5000"},



                  };

                if (search != null && search != string.Empty)
                {
                    var strings = search.ToLower().Split(' ');
                    listaActividad = dbModel.actividad.Include(x => x.oportunidades).Include(x => x.usuario.contactos).ToList();

                    foreach (var splitString in strings)
                    {
                        listaActividad = listaActividad.Where(x => x.creada_por.ToLower().Contains(splitString) || x.descripcion!=null && x.descripcion.ToLower().Contains(splitString) || x.estado.ToLower().Contains(splitString) || x.titulo.ToLower().ToString().Contains(splitString) || x.tipo_actividad.ToLower().Contains(splitString) || x.oportunidades.tema.ToLower().Contains(splitString) || x.usuario.contactos.nombres.ToLower().Contains(splitString) || x.usuario.contactos.apellidos.ToLower().Contains(splitString)).ToList();
                    }
                }

                else
                {
                    listaActividad = dbModel.actividad.Include(x => x.oportunidades).Include(x => x.usuario.contactos).ToList<actividad>();

                }


                ViewBag.SortCreadaPor = string.IsNullOrEmpty(sortBy) ? "creada_por_desc" : "";
                ViewBag.SortFechaI = sortBy == "fechaI" ? "fechaI_desc" : "fechaI";
                ViewBag.SortFechaV = sortBy == "fechaV" ? "fechaV_desc" : "fechaV";
                ViewBag.SortTitulo = sortBy == "titulo" ? "titulo_desc" : "titulo";
                ViewBag.SortDescr = sortBy == "descripcion" ? "descripcion_descr" : "descripcion";
                ViewBag.SortCreadaPor = sortBy == "creada_por" ? "creada_por_desc" : "creada_por";
                ViewBag.SortEstado = sortBy == "estado" ? "estado_desc" : "estado";
                ViewBag.SortTipoAct = sortBy == "tipo_actividad" ? "tipo_actividad_desc" : "tipo_actividad";
                ViewBag.SortTema = sortBy == "tema" ? "tema_desc"  : "tema";
                ViewBag.SortContacto = sortBy == "contacto" ? "contacto_desc" : "contacto";
                switch (sortBy)
                {
                    case "creada_por_desc":
                        listaActividad = listaActividad.OrderByDescending(x => x.creada_por).ToList();
                        break;
                    case "fechaI":
                        listaActividad = listaActividad.OrderBy(x => x.fecha_inicio).ToList();
                        break;
                    case "fechaI_desc":
                        listaActividad = listaActividad.OrderByDescending(x => x.fecha_inicio).ToList();
                        break;
                    case "fechaV":
                        listaActividad = listaActividad.OrderBy(x => x.fecha_vencimiento).ToList();
                        break;
                    case "fechaV_desc":
                        listaActividad = listaActividad.OrderByDescending(x => x.fecha_vencimiento).ToList();
                        break;
                    case "titulo":
                        listaActividad = listaActividad.OrderBy(x => x.titulo).ToList();
                        break;
                    case "titulo_desc":
                        listaActividad = listaActividad.OrderByDescending(x => x.titulo).ToList();
                        break;
                    case "estado":
                        listaActividad = listaActividad.OrderBy(x => x.estado).ToList();
                        break;
                    case "estado_desc":
                        listaActividad = listaActividad.OrderByDescending(x => x.estado).ToList();
                        break;
                    case "tipo_actividad":
                        listaActividad = listaActividad.OrderBy(x => x.tipo_actividad).ToList();
                        break;
                    case "tipo_actividad_desc":
                        listaActividad = listaActividad.OrderByDescending(x => x.tipo_actividad).ToList();
                        break;
                    case "tema":
                        listaActividad = listaActividad.OrderBy(x => x.oportunidades.tema).ToList();
                        break;
                    case "tema_desc":
                        listaActividad = listaActividad.OrderByDescending(x => x.oportunidades.tema).ToList();
                        break;
                    case "contacto":
                        listaActividad = listaActividad.OrderBy(x => x.usuario.contactos.nombres).ThenBy(x=>x.usuario.contactos.apellidos).ToList();
                        break;
                    case "contacto_desc":
                        listaActividad = listaActividad.OrderByDescending(x => x.usuario.contactos.nombres).ThenBy(x=>x.usuario.contactos.apellidos).ToList();
                        break;
                    case "descripcion":
                        listaActividad = listaActividad.OrderBy(x => x.descripcion).ToList();
                        break;
                    case "descripcion_descr":
                        listaActividad = listaActividad.OrderByDescending(x => x.descripcion).ToList();
                        break;
                    default:
                        listaActividad = listaActividad.OrderBy(x => x.creada_por).ToList();
                        break;
                }


                return View(listaActividad.ToList<actividad>().ToPagedList(page ?? 1, nn ?? 10));
            }
        }

        public ActionResult Crear_Actividad(int? id_op)
        {
            actividad model = new actividad();
            using (proyectob_dbEntities db = new proyectob_dbEntities())
            {
                model.usuarioList = db.usuario.Where(x=>x.estado=="activo").OrderBy(x=>x.contactos.nombres).ThenBy(x=>x.contactos.apellidos).Include(x=>x.contactos).ToList();
                //model.empresaList = db.empresa.ToList();
                model.oList = db.oportunidades.ToList();

                model.id_oportunidad = id_op ?? default(int);




                return PartialView(model);
            }

        }

        public ActionResult Crear_ActividadF()
        {
            actividad model = new actividad();
            using (proyectob_dbEntities db = new proyectob_dbEntities())
            {
                model.oList = db.oportunidades.ToList();
                //model.empresaList = db.empresa.ToList();
                model.usuarioList = db.usuario.Where(x=>x.estado=="activo").OrderBy(x => x.contactos.nombres).ThenBy(x => x.contactos.apellidos).Include(x=>x.contactos).ToList();

                return PartialView(model);
            }

        }
        public ActionResult Crear_Llamada(int? id_op)
        {
            actividad model = new actividad();
            using (proyectob_dbEntities db = new proyectob_dbEntities())
            {
                model.usuarioList = db.usuario.Where(x=>x.estado=="activo").OrderBy(x => x.contactos.nombres).ThenBy(x => x.contactos.apellidos).Include(x => x.contactos).ToList();
                //model.empresaList = db.empresa.ToList();
                model.oList = db.oportunidades.ToList();

                model.id_oportunidad = id_op ?? default(int);


                return PartialView(model);
            }
        }
        public ActionResult Crear_Mail(int? id_op)
        {
            actividad model = new actividad();
            using (proyectob_dbEntities db = new proyectob_dbEntities())
            {
                model.usuarioList = db.usuario.Where(x => x.estado == "activo").OrderBy(x => x.contactos.nombres).ThenBy(x => x.contactos.apellidos).Include(x => x.contactos).ToList();
                //model.empresaList = db.empresa.ToList();
                model.oList = db.oportunidades.ToList();

                model.id_oportunidad = id_op ?? default(int);


                return PartialView(model);
            }
        }
        public ActionResult Crear_Reunion(int? id_op)
        {
            actividad model = new actividad();
            using (proyectob_dbEntities db = new proyectob_dbEntities())
            {
                model.usuarioList = db.usuario.Where(x => x.estado == "activo").OrderBy(x => x.contactos.nombres).ThenBy(x => x.contactos.apellidos).Include(x => x.contactos).ToList();
                //model.empresaList = db.empresa.ToList();
                model.oList = db.oportunidades.ToList();

                model.id_oportunidad = id_op ?? default(int);


                return PartialView(model);

ProyectoB/Views/Oportunidades/Agregar_Contacto.cshtml
@model WebApplication9.Models.contactos


<style>
    .ui-dialog-title {
        font-size: 120%;
    }

    .control-label {
        font-weight: bold;
    }
</style>

<script src="~/Content/Scripts/jquery.validate.js"></script>
<script src="~/Content/Scripts/jquery-ui.js"></script>
<script src="~/Content/Scripts/jquery.validate.unobtrusive.js"></script>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                <div class="row col-md-12">
                    <div class="col">
                        @Html.LabelFor(model => model.rut, htmlAttributes: new { @class = "control-label col-md-2" })
                        @Html.EditorFor(model => model.rut, new { htmlAttributes = new { @class = "form-control", required = "required", onchange = "checkRut(this)" } })
                        @Html.ValidationMessageFor(model => model.rut, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

                <div class="form-group">
                    <div class="row col-md-12">

                        <div class="col">
                            @Html.LabelFor(model => model.nombres, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.EditorFor(model => model.nombres, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                            @Html.ValidationMessageFor(model => model.nombres, "", new { @class = "text-danger" })
                        </div>

                        <div class="col">
                            @Html.LabelFor(model => model.apellidos, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.EditorFor(model => model.apellidos, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                            @Html.ValidationMessageFor(model => model.apellidos, "", new { @class = "text-danger" })
                        </div>
                    </div>

                </div>


                <div class="form-group">
                    <div class="row col-md-12">

                        <div class="col">
                            @Html.LabelFor(model => model.tcel, htmlAttributes: new { @class = "control-label col-md-2 text-nowrap" })
                            @Html.EditorFor(model => model.tcel, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                            @Html.ValidationMessageFor(model => model.tcel, "", new { @class = "text-danger" })
                        </div>

                        <div class="col">
                            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                            @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>


                <div class="form-group">
                    <div class="row col-md-12">

                        <div class="col">
                            @Html.LabelFor(model => model.comentario, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.EditorFor(model => model.comentario, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                            @Html.ValidationMessageFor(model => model.comentario, "", new { @class = "text-danger" })
                        </div>

                    </div>
                </div>
                <div class="form-group">
                    <div class="col">
                        @Html.LabelFor(model => model.curriculum, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div><input type="file" name="file" id="file" /></div>
                        <br><br>
                        @Html.ValidationMessageFor(model => model.curriculum, "", new { @class = "text-danger" })
                    </div>
                </div>




                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Crear" class="btn btn-primary" />
                    </div>
                </div>

        }
    </div>
    <script>

    function checkRut(rut) {
        // Despejar Puntos
        var valor = rut.value.replace('.', '');
        // Despejar Guión
        valor = valor.replace('-', '');

        // Aislar Cuerpo y Dígito Verificador
        cuerpo = valor.slice(0, -1);
        dv = valor.slice(-1).toUpperCase();

        // Formatear RUN
        rut.value = cuerpo + '-' + dv

        // Si no cumple con el mínimo ej. (n.nnn.nnn)
        if (cuerpo.length < 7) { rut.setCustomValidity("RUT Incompleto"); return false; }

        // Calcular Dígito Verificador
        suma = 0;
        multiplo = 2;

        // Para cada dígito del Cuerpo
        for (i = 1; i <= cuerpo.length; i++) {

            // Obtener su Producto con el Múltiplo Correspondiente
            index = multiplo * valor.charAt(cuerpo.length - i);

            // Sumar al Contador General
            suma = suma + index;

            // Consolidar Múltiplo dentro del rango [2,7]
            if (multiplo < 7) { multiplo = multiplo + 1; } else { multiplo = 2; }

        }

        // Calcular Dígito Verificador en base al Módulo 11
        dvEsperado = 11 - (suma % 11);

        // Casos Especiales (0 y K)
        dv = (dv == 'K') ? 10 : dv;
        dv = (dv == 0) ? 11 : dv;

        // Validar que el Cuerpo coincide con su Dígito Verificador
        if (dvEsperado != dv) { rut.setCustomValidity("RUT Inválido"); return false; }

        // Si todo sale bien, eliminar errores (decretar que es válido)
        rut.setCustomValidity('');
    }
    $("#my-dialog2").dialog('option', 'title', 'Crear Contacto');
    $("#my-dialogCO").dialog('option', 'title', 'Crear Usuario');


    </script>





    <div>
        @Html.ActionLink("Volver al índice", "/Index_Contacto")
    </div>

}

ProyectoB/Views/Oportunidades/Delete_Oportunidad.cshtml
@model WebApplication9.Models.oportunidades

<h3>¿Está seguro de eliminar este registro?</h3>
<div>
    <hr />
    @Html.HiddenFor(model => model.id, new { @id = "idOp" })

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.fecha_creacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fecha_creacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fecha_vencimiento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fecha_vencimiento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cupos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cupos)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tema)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tema)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.estado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.contacto_empresa.id_contacto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.contacto_empresa.id_contacto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.usuario.id_contacto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.usuario.id_contacto)
        </dd>

    </dl>
    @Html.ValidationMessage("error", "", new { @class = "text-danger" })




    @using (Ajax.BeginForm(null, null, new AjaxOptions { HttpMethod = "POST" }, new { id = "formEliminarOp" })) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-primary" /> |
            @Html.ActionLink("Volver al índice", "Index_Oportunidades")
        </div>
    }

</div>
<script>

    $('#formEliminarOp').on("submit", function (e) {
        e.preventDefault();
        $.ajax({
            type: "POST",
            url: "/Oportunidades/Delete_Oportunidad/",
            data: { id: $('#idOp').val() },
            success: function (result) {

                if (result.success) {
                    alert('Registro Eliminado con éxito');

                    if ($('#my-dialogEmpresa').dialog('isOpen') == true) {
                        var id_empresa = '@ViewBag.id_empresa';
                            $('#my-dialogEmpresa').load('/Empresas/Details_Empresa/' + id_empresa, function () {
                                $(this).dialog('open');
                            });
                    }


                    else if ($('#my-dialogUsers').dialog('isOpen') == true) {
                        var id_usuario = '@ViewBag.id_usuario';
                        $('#my-dialogUsers').load('/Usuarios/Details2_Usuario/' + id_usuario, function () {
                            $(this).dialog('open');
                        });

                            }

                        if ($('#my-dialog2').dialog('isOpen') == true) {
                            $('#my-dialog2').dialog('close');
                        }
                        else {
                            location.reload();
                        }
                    }
                    else {
                        alert('No se pudo eliminar el registro');
                    }
                },
                error: function (xhr, textStatus, errorThrown) {
                    alert('Error!!');
                }
        });

        });
    $("#my-dialog2").dialog('option', 'title', 'Eliminar Oportunidad');
    $("#my-dialogOps").dialog('option', 'title', 'Eliminar Oportunidad');

</script>

ProyectoB/Views/Oportunidades/Detalle_Oportunidad.cshtml
@model IEnumerable<WebApplication9.Models.actividad>
<div class="partial">

    <div id="my-dialog2"></div>

    <p>
        @Html.ActionLink("Tarea", "Crear_Actividad", "Actividades", new { id_op = @ViewBag.idOp }, new { @class = "modolo2 btn btn-primary btn-large" })
        @Html.ActionLink("Llamada", "Crear_Llamada", "Actividades", new { id_op = @ViewBag.idOp }, new { @class = "modolo2 btn btn-primary btn-large" })
        @Html.ActionLink("Mail", "Crear_Mail", "Actividades", new { id_op = @ViewBag.idOp }, new { @class = "modolo2 btn btn-primary btn-large" })
        @Html.ActionLink("Reunión", "Crear_Reunion", "Actividades", new { id_op = @ViewBag.idOp }, new { @class = "modolo2 btn btn-primary btn-large" })
        @Html.DropDownList("listaL", new SelectList(ViewBag.ListaL, "Value", "Text"), "Seleccione Estado", new { @id = "ddlEstado", @style = "width:200px;", @onchange = "javascript:GetEstados(this.value);" })

        @Html.Hidden("id_oportunidad",(string)@ViewBag.idOp, new {@id= "id_oportunidad"})
        <h1>Actividades de Oportunidad @ViewBag.idOp</h1>

    </p>
    <style>
        .descr {
            max-width: 200px;
            white-space: nowrap;
            overflow: hidden;
        }

            .descr:hover {
                text-overflow: clip;
                white-space: normal;
                word-break: normal;
            }
        .ui-dialog-title {
            font-size: 120%;
        }

        .control-label {
            font-weight: bold;
        }
    </style>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayName("ID de Oportunidad")
            </th>
            <th>
                @Html.DisplayName("Contacto Asignado")
            </th>
            <th>
                @Html.DisplayName("Fecha de Inicio")
            </th>
            <th>
                @Html.DisplayName("Fecha de Vencimiento")
            </th>

            <th>
                @Html.DisplayName("Título")
            </th>
            <th>
                @Html.DisplayName("Descripción")
            </th>
            <th>
                @Html.DisplayName("Creada Por")
            </th>

            <th>
                @Html.DisplayName("Tipo de Actividad")
            </th>

            <th>
                @Html.DisplayName("Estado")
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.oportunidades.id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.usuario.contactos.FullName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.fecha_inicio)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.fecha_vencimiento)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.titulo)
                </td>
                <td class="descr">
                    @Html.DisplayFor(modelItem => item.descripcion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.creada_por)

                <td>
                    @Html.DisplayFor(modelItem => item.tipo_actividad)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.estado)
                </td>
                <td>
                    @*@Html.ActionLink("Edit", "Edit", new { id=item.id }, new { @class = "modolo2 btn btn-primary btn-large" }) |
                        @Html.ActionLink("Details", "Details", new { id=item.id }, new { @class = "modolo2 btn btn-primary btn-large" }) |
                        @Html.ActionLink("Delete", "Delete", new { id=item.id }, new { @class = "modolo2 btn btn-primary btn-large" })*@
                    @Html.ActionLink("Finalizar", "Finalizar_Actividad", "Actividades", new { id = item.id }, new { @class = "modolo2 btn btn-primary btn-large" })
                </td>
            </tr>
        }

    </table>
</div>

<div id="results"></div>

<script type="text/javascript">


    $(function () {
        $('#my-dialog2').dialog({
            autoOpen: false,
            width: 'auto',
            height: 'auto',
            resizable: false,
            modal: true,
            open: function () {
                jQuery('.ui-widget-overlay').bind('click', function () {
                    jQuery('#my-dialog2').dialog('close');
                })
            }

        });

        $('.modolo2').click(function () {
            $('#my-dialog2').load(this.href, function () {
                $(this).dialog('open');
            });
            return false;
        });
    });
    //function GetEstados(_id) {
      //  var url = "/Actividades/GetActsbyEstado/";
        //var url = "Url.Action(GetContactobyEmpresa)";



    function GetEstados(_id) {
        var url = "/Oportunidades/Detalle_Oportunidad/";
        $.ajax({
            type: "POST",
            contentType: "application/json; charset=utf-8",
            url: "/Oportunidades/Detalle_Oportunidad/",
            data: JSON.stringify({ id_ops: $("#id_oportunidad").val(), estado:_id }),
            dataType: "html",
            success: function (data) {
                var newHTML = data;
                //$("#ddlEstado").val(estado);
                $("#my-dialogOps").html(newHTML);            },
            error: function (reponse) {
                alert("error : " + reponse.responseText);
            }

        });

    }

    $("#my-dialog2").dialog('option', 'title', 'Detalle Oportunidad');
    $("#my-dialogOps").dialog('option', 'title', 'Detalle Oportunidad');
    $("#my-dialog").dialog('option', 'title', 'Detalle Oportunidad');

</script>