ProyectoB/Models/contacto_empresa.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    using System.Web.Script.Serialization;

    public partial class contacto_empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public contacto_empresa()
        {
            this.oportunidades = new HashSet<oportunidades>();
            this.fecha_inicio_rel = System.DateTime.Now;
        }

        public int id { get; set; }
        [Display(Name = "Empresa")]
        [Required(ErrorMessage = "Seleccione Empresa")]
        public int id_empresa { get; set; }
        [Display(Name = "Contacto")]
        [Required(ErrorMessage = "Seleccione Contacto")]
        public int id_contacto { get; set; }
        [Display(Name = "Fecha de Inicio")]
        [Required(ErrorMessage = "Debe seleccionar Fecha")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime fecha_inicio_rel { get; set; }
        [Display(Name = "Fecha de Término")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> fecha_termino_rel { get; set; }
        [Display(Name = "Cargo")]
        public string cargo { get; set; }
        [Display(Name = "Teléfono Fijo")]
        [Required(ErrorMessage = "Seleccione Teléfono Fijo")]
        [DataType(DataType.Text)]
        public int telefono_fijo { get; set; }
        [Display(Name = "Teléfono Celular")]
        [Required(ErrorMessage = "Seleccione Teléfono Celular")]
        [DataType(DataType.Text)]
        public int telefono_celular { get; set; }

        public List<empresa> empresaListI;
        public List<contactos> contactoListI;


        [ScriptIgnore]
        public virtual empresa empresa { get; set; }
        public virtual contactos contactos { get; set; }

        public List<SelectListItem> empresaListSI { get; internal set; }
        public List<SelectListItem> contactosListSI { get; internal set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<oportunidades> oportunidades { get; set; }

        public string FullName
        {
            get
            {
                return contactos.nombres + " " + contactos.apellidos;
            }
        }
        public string EmpresaName
        {
            get
            {
                return empresa.razon_social;
            }
        }



    }
}

ProyectoB/Controllers/Contacto_EmpresaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.Entity;
using PagedList;
using WebApplication9.Models;
using System.Net;

namespace WebApplication9.Controllers
{
    public class Contacto_EmpresaController : Controller
    {
        // GET: Contacto_Empresa
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Index_Empresa_Contacto(int? page, string search, int? nn, string sortBy)

        {
            List<contacto_empresa> ListacEmpresa = new List<contacto_empresa>();

            ViewBag.NumeroR = new List<SelectListItem>()


            {
                    new SelectListItem() {Text="10", Value="10"},
                    new SelectListItem() {Text="20", Value="20"},
                    new SelectListItem() {Text="40", Value="40"},
                    new SelectListItem() {Text="60", Value="60"},
                    new SelectListItem() {Text="100", Value="100"},
                    new SelectListItem() {Text="200", Value="200"},
                    new SelectListItem() {Text="500", Value="500"},
                    new SelectListItem() {Text="1000", Value="1000"},
                    new SelectListItem() {Text="2000", Value="2000"},
                    new SelectListItem() {Text="5000", Value="5000"},



                  };
            using (proyectob_dbEntities dbModel = new proyectob_dbEntities())
            {

                if (search != String.Empty && search != null)
                {
                    var strings = search.ToLower().Split(' ');
                    ListacEmpresa = dbModel.contacto_empresa.Include(x => x.empresa).Include(x => x.contactos).ToList();

                    foreach (var splitString in strings)
                    {
                        ListacEmpresa = ListacEmpresa.Where(x => x.contactos.nombres.ToLower().Contains(splitString) || x.contactos.apellidos.ToLower().Contains(splitString) || x.empresa.razon_social.ToLower().Contains(splitString) 
                        || x.cargo != null && x.cargo.ToLower().Contains(splitString) || x.telefono_celular.ToString().Contains(splitString) 
                        || x.telefono_fijo.ToString().Contains(splitString) || x.contactos.rut.ToLower().Contains(splitString) 
                        || x.empresa.rut.ToLower().Contains(splitString)).ToList();
                    }
                }
                else
                {
                    ListacEmpresa = dbModel.contacto_empresa.Include(x => x.empresa).Include(x => x.contactos).ToList();

                }

                ViewBag.SortNEmpresa = string.IsNullOrEmpty(sortBy) ? "name_empresa_desc" : "";
                ViewBag.SortNContacto = sortBy == "nombre_contacto" ? "nombre_contacto_desc" : "nombre_contacto";
                ViewBag.SortFechaI = sortBy == "fechaI" ? "fechaI_desc" : "fechaI";
                ViewBag.SortFechaT = sortBy == "fechaT" ? "fechaT_desc" : "fechaT";
                ViewBag.SortCargo = sortBy == "cargo" ? "cargo_desc" : "cargo";
                ViewBag.SortTFijo = sortBy == "tfijo" ? "tfijo_desc" : "tfijo";
                ViewBag.SortTCelular = sortBy == "tcelular" ? "tcelular_desc" : "tcelular";
                ViewBag.SortRutEmpresa = sortBy == "rut_empresa" ? "rut_empresa_desc" : "rut_empresa";
                ViewBag.SortRutContacto = sortBy == "rut_contacto" ? "rut_contacto_desc" : "rut_contacto";

                switch (sortBy)
                {
                    case "name_empresa_desc":
                        ListacEmpresa = ListacEmpresa.OrderByDescending(x => x.empresa.razon_social).ToList();
                        break;
                    case "nombre_contacto":
                        ListacEmpresa = ListacEmpresa.OrderBy(x => x.contactos.nombres).ThenBy(x=>x.contactos.nombres).ToList();
                        break;
                    case "nombre_contacto_desc":
                        ListacEmpresa = ListacEmpresa.OrderByDescending(x => x.contactos.nombres).ThenBy(x => x.contactos.nombres).ToList();
                        break;
                    case "fechaI_desc":
                        ListacEmpresa = ListacEmpresa.OrderByDescending(x => x.fecha_inicio_rel).ToList();
                        break;
                    case "fechaI":
                        ListacEmpresa = ListacEmpresa.OrderBy(x => x.fecha_inicio_rel).ToList();
                        break;
                    case "fechaT_desc":
                        ListacEmpresa = ListacEmpresa.OrderByDescending(x => x.fecha_termino_rel).ToList();
                        break;
                    case "fechaT":
                        ListacEmpresa = ListacEmpresa.OrderBy(x => x.fecha_termino_rel).ToList();
                        break;
                    case "cargo_desc":
                        ListacEmpresa = ListacEmpresa.OrderByDescending(x => x.cargo).ToList();
                        break;
                    case "cargo":
                        ListacEmpresa = ListacEmpresa.OrderBy(x => x.cargo).ToList();
                        break;
                    case "tfijo_desc":
                        ListacEmpresa = ListacEmpresa.OrderByDescending(x => x.telefono_fijo).ToList();
                        break;
                    case "tfijo":
                        ListacEmpresa = ListacEmpresa.OrderBy(x => x.telefono_fijo).ToList();
                        break;
                    case "tcelular_desc":
                        ListacEmpresa = ListacEmpresa.OrderByDescending(x => x.telefono_celular).ToList();
                        break;
                    case "tcelular":
                        ListacEmpresa = ListacEmpresa.OrderBy(x => x.telefono_celular).ToList();
                        break;
                    case "rut_empresa_desc":
                        ListacEmpresa = ListacEmpresa.OrderByDescending(x => x.empresa.rut).ToList();
                        break;
                    case "rut_empresa":
                        ListacEmpresa = ListacEmpresa.OrderBy(x => x.empresa.rut).ToList();
                        break;
                    case "rut_contacto":
                        ListacEmpresa = ListacEmpresa.OrderBy(x => x.contactos.rut).ToList();
                        break;
                    case "rut_contacto_desc":
                        ListacEmpresa = ListacEmpresa.OrderByDescending(x => x.contactos.rut).ToList();
                        break;
                    default:
                        ListacEmpresa = ListacEmpresa.OrderBy(x => x.empresa.razon_social).ToList();
                        break;
                }

                return View(ListacEmpresa.ToList<contacto_empresa>().ToPagedList(page ?? 1, nn ?? 10));
            }

            //return View(ListacEmpresa);




        }
        public ActionResult Crear_contacto_empresa()
        {
            contacto_empresa model = new contacto_empresa();
            using (proyectob_dbEntities db = new proyectob_dbEntities())
            {
                //model.rolesList = db.roles.ToList();
                model.empresaListI = db.empresa.OrderBy(x=>x.razon_social).ToList();
                model.contactoListI = db.contactos.OrderBy(x=>x.nombres).ThenBy(x=>x.apellidos).ToList();


            }
            return PartialView(model);
        }
        public ActionResult Crear_contacto_empresaF()
        {
            contacto_empresa model = new contacto_empresa();
            using (proyectob_dbEntities db = new proyectob_dbEntities())
            {
                //model.rolesList = db.roles.ToList();
                model.empresaListI = db.empresa.OrderBy(x=>x.razon_social).ToList();
                model.contactoListI = db.contactos.OrderBy(x => x.nombres).ThenBy(x=>x.apellidos).ToList();


            }
            return View(model);
        }
        [HttpPost]
        [ValidateAjax]
        public ActionResult Crear_contacto_empresa(contacto_empresa contactoEmpresa)
        {


            using (proyectob_dbEntities dbModel = new proyectob_dbEntities())
            {


                //contactos contacto = new contactos();
                //contacto = contactoEmpresa.contactos;
                //contactoEmpresa.contactos.id = contactoEmpresa.id_contacto;
                //contactoEmpresa.contactos.curriculum = "";


                //dbModel.contactos.Add(contactoEmpresa.contactos);

                //contactoEmpresa.id_empresa = contactoEmpresa.id_empresa;
                //contactoEmpresa.fecha_inicio_rel = System.DateTime.Today;
                //contactoEmpresa.id_contacto = contactoEmpresa.id_contacto;
                dbModel.contacto_empresa.Add(contactoEmpresa);

                dbModel.SaveChanges();

                return Json(new { success = true }, JsonRequestBehavior.AllowGet);

            }
        }
        [HttpPost]
        public ActionResult Crear_contacto_empresaF(contacto_empresa contactoEmpresa)
        {


            using (proyectob_dbEntities dbModel = new proyectob_dbEntities())
            {


                //contactos contacto = new contactos();
                //contacto = contactoEmpresa.contactos;
                // contactoEmpresa.contactos.id = contactoEmpresa.id_contacto;
                //contactoEmpresa.contactos.curriculum = "";


                //dbModel.contactos.Add(contactoEmpresa.contactos);

                //contactoEmpresa.id_empresa = contactoEmpresa.id_empresa;
                //contactoEmpresa.fecha_inicio_rel = System.DateTime.Today;
                //contactoEmpresa.id_contacto = contactoEmpresa.id_contacto;
                if (ModelState.IsValid)
                {
                    dbModel.contacto_empresa.Add(contactoEmpresa);
                    dbModel.SaveChanges();
                    ModelState.Clear();


                    contactoEmpresa = new contacto_empresa();

ProyectoB/Views/Contacto_Empresa/Crear_contacto_empresa.cshtml
@model WebApplication9.Models.contacto_empresa
<style>
    .custom-combobox {
        position: relative;
        display: inline-block;
    }

    .custom-combobox-toggle {
        position: absolute;
        top: 0;
        bottom: 0;
        margin-left: -1px;
        padding: 0;
    }

    .custom-combobox-input {
        margin: 0;
        padding: 5px 10px;
    }
</style>
<script src="~/Content/Scripts/jquery.validate.min.js"></script>
<script src="~/Content/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Content/Scripts/moment.js"></script>

@using (Ajax.BeginForm(null, null, new AjaxOptions { HttpMethod = "POST" }, new { id = "formCempresa" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.id_empresa, "Empresa", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-sm-6">
                @Html.DropDownListFor(model => model.id_empresa, new SelectList(Model.empresaListI, "id", "razon_social"), "Seleccione Empresa", new { @id = "ddlEs", style = "width:250px;", required = "required" })
                @Html.ValidationMessageFor(model => model.id_empresa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_contacto, "Contacto", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-sm-6">
                @Html.DropDownListFor(model => model.id_contacto, new SelectList(Model.contactoListI, "id", "FullName"), "Seleccione Usuario", new { required = "required" })
                @Html.ValidationMessageFor(model => model.id_contacto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fecha_inicio_rel, htmlAttributes: new { @class = "control-label col-md-2 text-nowrap" })
            <div class="col-sm-12">
                @Html.TextBoxFor(model => model.fecha_inicio_rel, new { @class = "Datepicker", @Value = Model.fecha_inicio_rel.ToString("dd-MM-yyyy"), required = "required", style="width:218px;"})
                @Html.ValidationMessageFor(model => model.fecha_inicio_rel, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.cargo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-sm-12">
                @Html.EditorFor(model => model.cargo, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.cargo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.telefono_fijo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-sm-12">
                @Html.EditorFor(model => model.telefono_fijo, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.telefono_fijo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.telefono_celular, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-sm-12">
                @Html.EditorFor(model => model.telefono_celular, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.telefono_celular, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}
<script type="text/javascript">
    $('#formCempresa').on("submit", function (e) {
        e.preventDefault();

        var contactoEmpresa = {
            id_empresa: $('#id_empresa').val(),
            id_contacto: $('#id_contacto').val(),
            fecha_inicio_rel: $('#fecha_inicio_rel').val(),
            cargo: $('#cargo').val(),
            telefono_fijo: $('#telefono_fijo').val(),
            telefono_celular: $('#telefono_celular').val()
        };

        var $form = $("#formCempresa");
        $.validator.unobtrusive.parse($form);

        if ($form.valid()) {

            $.ajax({
                type: "POST",
                url: "/Contacto_Empresa/Crear_Contacto_Empresa",
                content: "application/json; charset=utf-8",
                dataType: "json",
                data: $form.serialize(),
                success: function (response) {
                    alert('Registro ingresado con éxito');

                    if ($('#my-dialog2').dialog('isOpen') == true) {
                        $('#my-dialog2').dialog('close');
                        if ($('#my-dialogOps').dialog('isOpen') == true) {
                            $('#my-dialogOps').load('/Oportunidades/Crear_OportunidadP/', function () {
                                $(this).dialog('open');
                                var empresaSelect = document.getElementById('ddlstate');
                                var selectedEmpresa = Cookies.get('empresa');
                                empresaSelect.value = selectedEmpresa;

                                //Actualiza los contactos de la empresa en OportunidadP
                                GetCEmpresa(selectedEmpresa);

                            })
                        }
                    }
                    else {
                        location.reload();
                    }
                },
                error: function (xhr, textStatus, errorThrown) {
                    alert("Complete todos los campos");
                }
            });
        }


    });

    $(document).ready(function () {


        $('.Datepicker').datepicker({
            dateFormat: "dd-mm-yy",
            showStatus: true,
            showWeeks: true,
            currentText: 'Now',
            autoSize: true,
            gotoCurrent: true,
            showAnim: 'blind',
            highlightWeek: true
        });
    });

    $(function () {
        $.widget("custom.combobox", {
            _create: function () {
                this.wrapper = $("<span>")
                    .addClass("custom-combobox")
                    .insertAfter(this.element);

                this.element.hide();
                this._createAutocomplete();
                this._createShowAllButton();
            },

            _createAutocomplete: function () {
                var selected = this.element.children(":selected"),
                    value = selected.val() ? selected.text() : "";

                this.input = $("<input>")
                    .appendTo(this.wrapper)
                    .val(value)
                    .attr("title", "")
                    .addClass("custom-combobox-input ui-widget ui-widget-content ui-state-default ui-corner-left")
                    .autocomplete({
                        delay: 0,
                        minLength: 0,
                        source: $.proxy(this, "_source")
                    })
                    .tooltip({
                        classes: {
                            "ui-tooltip": "ui-state-highlight"
                        }
                    });

                this._on(this.input, {
                    autocompleteselect: function (event, ui) {
                        ui.item.option.selected = true;
                        this._trigger("select", event, {
                            item: ui.item.option
                        });
                    },

                    autocompletechange: "_removeIfInvalid"
                });
            },

            _createShowAllButton: function () {
                var input = this.input,
                    wasOpen = false;

                $("<a>")
                    .attr("tabIndex", -1)
                    .attr("title", "Mostrar Todos")
                    .tooltip()
                    .appendTo(this.wrapper)
                    .button({
                        icons: {
                            primary: "ui-icon-triangle-1-s"
                        },
                        text: false
                    })
                    .removeClass("ui-corner-all")
                    .addClass("custom-combobox-toggle ui-corner-right")
                    .on("mousedown", function () {
                        wasOpen = input.autocomplete("widget").is(":visible");
                    })
                    .on("click", function () {
                        input.trigger("focus");

                        // Close if already visible
                        if (wasOpen) {
                            return;
                        }

                        // Pass empty string as value to search for, displaying all results
                        input.autocomplete("search", "");
                    });
            },

            _source: function (request, response) {
                var matcher = new RegExp($.ui.autocomplete.escapeRegex(request.term), "i");
                response(this.element.children("option").map(function () {
                    var text = $(this).text();
                    if (this.value && (!request.term || matcher.test(text)))
                        return {
                            label: text,
                            value: text,
                            option: this
                        };
                }));
            },

            _removeIfInvalid: function (event, ui) {

                // Selected an item, nothing to do
                if (ui.item) {
                    return;
                }

                // Search for a match (case-insensitive)
                var value = this.input.val(),
                    valueLowerCase = value.toLowerCase(),
                    valid = false;
                this.element.children("option").each(function () {
                    if ($(this).text().toLowerCase() === valueLowerCase) {
                        this.selected = valid = true;
                        return false;
                    }
                });

                // Found a match, nothing to do
                if (valid) {
                    return;
                }

                // Remove invalid value
                this.input
                    .val("")
                    .attr("title", value + " no se encontró ningun registro")
                    .tooltip("open");
                this.element.val("");
                this._delay(function () {
                    this.input.tooltip("close").attr("title", "");
                }, 2500);
                this.input.autocomplete("instance").term = "";
            },

            _destroy: function () {
                this.wrapper.remove();
                this.element.show();
            }
        });

        $("#ddlEs").combobox();
        $("#id_contacto").combobox();
        $("#toggle").on("click", function () {
            $("#ddlEs").toggle();
            $("#id_contacto").toggle();



        });

    });

    //Para que no aparezca el error de que debe ser una fecha
    $(function () {
        $.validator.methods.date = function (value, element) {
            return this.optional(element) || moment(value, "DD-MM-YYYY", true).isValid();
        }
    });
    $("#my-dialogCO").dialog('option', 'title', 'Crear Contacto-Empresa');
    $("#my-dialog2").dialog('option', 'title', 'Crear Contacto-Empresa');

</script> 

<div>
    @Html.ActionLink("Volver al índice", "/Index_Empresa_Contacto")
</div>

ProyectoB/Views/Contacto_Empresa/Index_Empresa_Contacto.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<WebApplication9.Models.contacto_empresa>

@{
    ViewBag.Title = "Contacto Empresa";
    Layout = "~/Views/Proyectob/Shared/_Layout.cshtml";
}



@*Html.ActionLink("Crear nuevo Contacto Empresa", "Create_Empresa_Contacto")*@


@using (Html.BeginForm("/index_empresa_contacto", "Contacto_Empresa", FormMethod.Get))
{
    <div class="form-group form-inline float-right m-1">
        
            @Html.ActionLink("Crear", "crear_contacto_empresa", null, new { @class = "modolo btn btn-primary btn-large m-1" })
            @Html.TextBox("search",null, new { @style = "width:200px;", @class = "form-control" }) <input type="submit" value="Buscar" class="btn btn-secondary" />
            @Html.DropDownList("nn", new SelectList(ViewBag.NumeroR, "Value", "Text"), new { @onchange = "this.form.submit()", @class = "form-control" })
            @Html.ActionLink("Mostrar todos", "Index_Empresa_Contacto")
        
    </div>


}

<div id="my-dialogEmpresaC"></div>

    <table class="table table-striped" id="medetai">
        <thead class="thead-light">
            <tr>

                <th>
                    @Html.ActionLink("Nombre Empresa", "index_empresa_contacto", new { sortBy = ViewBag.SortNEmpresa, search = Request.QueryString["search"], nn = Request.QueryString["nn"] })
                </th>
                <th>
                    @Html.ActionLink("Nombre Contacto", "index_empresa_contacto", new { sortBy = ViewBag.SortNContacto, search = Request.QueryString["search"], nn = Request.QueryString["nn"] })
                </th>

                <th>
                    @Html.ActionLink("Fecha Inicio", "index_empresa_contacto", new { sortBy = ViewBag.SortFechaI, search = Request.QueryString["search"], nn = Request.QueryString["nn"] })
                </th>
                <th>
                    @Html.ActionLink("Fecha Termino", "index_empresa_contacto", new { sortBy = ViewBag.SortFechaT, search = Request.QueryString["search"], nn = Request.QueryString["nn"] })
                </th>
                <th>
                    @Html.ActionLink("Cargo", "index_empresa_contacto", new { sortBy = ViewBag.SortCargo, search = Request.QueryString["search"], nn = Request.QueryString["nn"] })
                </th>
                <th>
                    @Html.ActionLink("Teléfono Fijo", "index_empresa_contacto", new { sortBy = ViewBag.SortTfijo, search = Request.QueryString["search"], nn = Request.QueryString["nn"] })
                </th>
                <th>
                    @Html.ActionLink("Celular", "index_empresa_contacto", new { sortBy = ViewBag.SortTcelular, search = Request.QueryString["search"], nn = Request.QueryString["nn"] })
                </th>
                <th>
                    @Html.ActionLink("Rut Empresa", "index_empresa_contacto", new { sortBy = ViewBag.SortRutEmpresa, search = Request.QueryString["search"], nn = Request.QueryString["nn"] })
                </th>
                <th>
                    @Html.ActionLink("Rut Contacto", "index_empresa_contacto", new { sortBy = ViewBag.SortRutContacto, search = Request.QueryString["search"], nn = Request.QueryString["nn"] })
                </th>
                <th></th>
            </tr>
        </thead>
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.EmpresaName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.fecha_inicio_rel)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.fecha_termino_rel)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.cargo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.telefono_fijo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.telefono_celular)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.empresa.rut)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.contactos.rut)
            </td>
            <td class="noExl">
                <div class="dropdown">
                    <button type="button" class="btn btn-info dropdown-toggle btn-sm" id="dlDropDown" data-toggle="dropdown">
                        Opciones
                    </button>
                    <div class="dropdown-menu">
                        @Html.ActionLink("Editar", "Edit_Contacto_Empresa", new { id = item.id }, new { @class = "modolo dropdown-item" })
                        @Html.ActionLink("Detalles", "Details_Contacto_Empresa", new { id = item.id }, new { @class = "modolo dropdown-item" })
                        @Html.ActionLink("Eliminar", "Delete_Contacto_Empresa", new { id = item.id }, new { @class = "modolo dropdown-item" })
                    </div>
                </div>
            </td>
        </tr>
    }

    </table>
<div class="col">
    <button id="export" class="btn btn-sm btn-secondary">Exportar</button>
    @Html.PagedListPager(Model, page => Url.Action("index_empresa_contacto", new { page, search = Request.QueryString["search"], nn = Request.QueryString["nn"], sortBy = Request.QueryString["sortBy"] }))


</div>
    @section scripts {
        <script type="text/javascript">
            $("#export").click(function () {
                $("#medetai").table2excel({
                    // exclude CSS class
                    exclude: ".noExl",
                    name: "Worksheet Name",
                    filename: "Contactos_Empresa" //do not include extension
                });
            });

            $(function () {
                $('#my-dialogEmpresaC').dialog({
                    autoOpen: false,
                    width: 'auto',
                    resizable: false,
                    modal: true,
                    open: function () {
                        jQuery('.ui-widget-overlay').bind('click', function () {
                            jQuery('#my-dialogEmpresaC').dialog('close');
                        })
                    }
                });

                $('.modolo').click(function () {
                    $('#my-dialogEmpresaC').load(this.href, function () {
                        $(this).dialog('open');
                    });
                    return false;
                });
            });
        </script>

    }